### ISSUE TITLE
No Secrets ?

### ISSUE THREAD

**Issue by lecler-i** [openfaas-incubator/faas-rancher#1]
Hello,

I just set-up openfaas and playing arround with rancher...
But rancher driver for faas doen't implement secrets ?

I have to manually set the secret myself on the newly created container...

https://github.com/openfaas/faas-netes/blob/master/SECRETS.md

It would be nice to add cattle secrets listed in the `stack.yml` when deploying the rancher container

**Comment by alexellis** [comment]
Hi there, @kenfdev may be able to speak to this. I'm not sure about your Rancher setup. Maybe you can list all the details and versions you are using? If in doubt regular Kubernetes is well-tested and fully working.

**Comment by kenfdev** [comment]
Hi @lecler-i ! Thanks for using `faas-rancher`.
Secrets aren't supported for `faas-rancher` and if I remember correctly, rancher 1.x never reached stable for secrets. And I'm assuming it won't be stable anymore because the cattle scheduler is going to be replaced with kubernetes.
I suggest you try out Rancher 2.0 since [it reached beta](https://rancher.com/rancher-2-0-now-feature-complete-enters-final-beta-phase/) a few days ago.
It's kubernetes under the hood and therefore `faas-netes` works the same as in any other kubernetes cluster.

**Comment by alexellis** [comment]
Thank you for answering Ken. Also if you'd rather not use a beta service right now with 2.0 you could use OpenFaaS directly with Kubernetes too.
